name: Update EPG XMLTV

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget mono-complete

      - name: Download WebGrab+Plus Linux v5.3
        run: |
          wget -O wg.tar.gz "https://webgrabplus.com/sites/default/files/download/SW/V5.3.0/WebGrabPlus_V5.3_install.tar.gz"
          mkdir -p ~/.wg++
          tar -xzf wg.tar.gz -C ~/.wg++

      - name: Verify installation
        run: |
          echo "Listing ~/.wg++ directory:"
          ls -R ~/.wg++

      - name: Copy configuration files
        run: |
          mkdir -p ~/.wg++/config
          cp wg-config.xml ~/.wg++/config/WebGrabPlus.config.xml
          cp ini_sources/*.ini ~/.wg++/siteini.pack/

      - name: Run wg++
        run: |
          ~/.wg++/wg++ -g  # generate default config if needed
          ~/.wg++/wg++     # grab EPG guide.xml

      - name: Output result
        run: |
          echo "Generated guide.xml:"
          ls -l ~/.wg++/guide.xml
