name: EPG1 Update
run-name: Updating the EPG 🎐
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Perl dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            libxml-parser-perl \
            libxml-simple-perl \
            libdatetime-perl \
            libwww-perl \
            libjson-perl \
            libhtml-parser-perl \
            libterm-readkey-perl \
            libfile-slurp-perl \
            git

      - name: Clone and build XMLTV with tv_grab_il
        run: |
          git clone https://github.com/XMLTV/xmltv.git
          cd xmltv
          ./configure
          make
          sudo make install
          which tv_grab_il

      - name: Generate EPG with tv_grab_il
        run: |
          tv_grab_il --output epg_il.xml --days 3 --quiet
      
      - name: Committing the new data
        run: |
          git config --global user.name 'bmk1239'
          git config --global user.email 'bmk1239@users.noreply.github.com'
          export NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          git add epg_il.xml
          git commit -am "Automated guide.xml update ($NOW)"
          git push
