name: Update EPG XMLTV

# on:
#   schedule:
#     - cron: '0 3 * * *'
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mono-complete
          # sudo apt-get install -y wget apt-transport-https
          # wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          # sudo dpkg -i packages-microsoft-prod.deb
          # sudo apt-get update
          # sudo apt-get install -y dotnet-runtime-6.0

      - name: Download WebGrab+Plus Linux
        run: |
          wget https://webgrabplus.com/sites/default/files/download/SW/V5.3.0/WebGrabPlus_V5.3_install.tar.gz
          mkdir -p ~/wgplus
          tar -xvzf WebGrabPlus_V5.3_install.tar.gz -C ~/wgplus

      # - name: Verify install
      #   run: |
      #     ls -l ~/wg++
      #     ls -l ~/wg++/bin
      #     ls -l ~/wg++/siteini.pack

      - name: Copy config & INI files
        run: |
          cp wg-config.xml ~/wgplus/.wg++/WebGrab++.config.example.xml
      #     mkdir -p ~/wg++/siteini.pack
      #     cp site.ini/*.ini ~/wg++/siteini.pack/

      - name: Run WebGrab+Plus (wg++)
        run: |
          ~/wgplus/.wg++/install.sh
          ~/wgplus/.wg++/run.net.sh

      - name: Commit and push EPG
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          cp ~/wg++/guide.xml xmltv.xml
          git add xmltv.xml
          git commit -m "Update EPG $(date)"
          git push
