name: update1

on:
  schedule:
    - cron: '0 4 * * *'  # every day at 7:00
  workflow_dispatch:    # also allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script1
      run: python script1.py

    - name: commit file1.xml
      uses: EndBug/add-and-commit@v9
      with:
        add: file1.xml
        message: "ci: update file1.xml"
