name: EPG1 Update
run-name: Updating the EPG 🎐
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cpanminus git libxml-simple-perl libdatetime-perl \
                                  libxmltv-perl libjson-perl libwww-perl libhtml-parser-perl \
                                  libfile-slurp-perl libterm-readkey-perl
          sudo cpanm XML::TV

      - name: Clone and install XMLTV with tv_grab_il
        run: |
          git clone https://github.com/XMLTV/xmltv.git
          cd xmltv
          ./configure
          make
          sudo make install
          which tv_grab_il

      - name: Grab EPG using tv_grab_il
        run: |
          tv_grab_il --days 3 --output epg_il.xml
      
      - name: Committing the new data
        run: |
          git config --global user.name 'bmk1239'
          git config --global user.email 'bmk1239@users.noreply.github.com'
          export NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          git add epg_il.xml
          git commit -am "Automated guide.xml update ($NOW)"
          git push
