name: Grab EPG

on:
  workflow_dispatch:

jobs:
  webgrab:
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET 6 runtime
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https ca-certificates gnupg
          wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-6.0

     - name: Download WebGrab+Plus 5.1.5‑beta (net6)
       run: |
          wget -q https://github.com/WGMaker/WebGrab/releases/download/V5.1.5-beta/WebGrabPlus-v5.1.5-beta-net6_x64.zip \
          -O WebGrabPlus_net6.zip
          unzip -q WebGrabPlus_net6.zip -d wgpp
          cp your-WebGrab-config.xml wgpp/

      - name: Run WG++
        run: |
          cd wgpp
          dotnet ./WebGrabPlus.dll
    
    - name: Upload XMLTV output
        uses: actions/upload-artifact@v4
        with:
          name: xmltv
          path: wgpp/guide.xml
