name: EPG1 Update
run-name: Updating the EPG 🎐
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Perl and build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cpanminus libxml-simple-perl libdatetime-perl \
            libwww-perl libhtml-parser-perl git

      - name: Clone XMLTV repo
        run: |
          git clone https://github.com/XMLTV/xmltv.git
          cd xmltv

      - name: Build and install XMLTV (including tv_grab_il)
        run: |
          cd xmltv
          perl Makefile.PL
          make
          sudo make install
          which tv_grab_il

      - name: Generate EPG using tv_grab_il
        run: |
          tv_grab_il --output epg_il.xml --days 3 --quiet
      
      - name: Committing the new data
        run: |
          git config --global user.name 'bmk1239'
          git config --global user.email 'bmk1239@users.noreply.github.com'
          export NOW=$(date +'%Y-%m-%dT%H:%M:%S')
          git add epg_il.xml
          git commit -am "Automated guide.xml update ($NOW)"
          git push
