name: Grab EPG

on:
  workflow_dispatch:

jobs:
  webgrab:
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET 6 runtime
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https ca-certificates gnupg
          wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-6.0

      - name: Download WebGrab+Plus 5.0 (net6)
        run: |
          wget -q https://github.com/WebGrabPlus/Guide/download/v5.0.0/WebGrabPlus_5.0.0_net6_x64.zip
          unzip -q WebGrabPlus_5.0.0_net6_x64.zip -d wgpp
          cp your-WebGrab-config.xml wgpp/

      - name: Run WG++
        run: |
          cd wgpp
          dotnet ./bin.net/WebGrab++.dll

      - name: Upload XMLTV output
        uses: actions/upload-artifact@v4
        with:
          name: xmltv
          path: wgpp/guide.xml
