name: 🇮🇱 tv_grab_il EPG via Docker

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:

jobs:
  grab-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Run tv_grab_il in Docker
        run: |
          mkdir -p epg
          docker run --rm -v ${{ github.workspace }}/epg:/data \
            ghcr.io/baruchmakro/xmltv-grabber:latest \
            tv_grab_il --output /data/epg_il.xml --days 3

      - name: Commit and push EPG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📺 EPG from tv_grab_il (via Docker)"
          file_pattern: epg/epg_il.xml
