# name: Grab EPG

# on:
#   workflow_dispatch:

# jobs:
#   webgrab:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Install .NET 6 runtime
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y wget apt-transport-https ca-certificates gnupg
#           wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
#           sudo dpkg -i packages-microsoft-prod.deb
#           sudo apt-get update
#           sudo apt-get install -y dotnet-runtime-6.0

#       - name: Download WebGrab+Plus 5.3.0
#         run: |
#           wget -q http://webgrabplus.com/sites/default/files/download/SW/V5.3.0/WebGrabPlus_V5.3_install.tar.gz
#           tar -xzf WebGrabPlus_V5.3_install.tar.gz
#       - name: Run WG++
#         run: |
#           cd .wg++
#           cp WebGrab++.config.example.xml WebGrab++.config.xml
#           dotnet bin.net/WebGrab+Plus.dll 
    
#       - name: Upload XMLTV output
#         uses: actions/upload-artifact@v4
#         with:
#           name: xmltv
#           path: .wg++/guide.xml
